# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'LalaTest' do
    # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
    use_frameworks!
    
    # Pods for LalaTest
    pod 'Alamofire', '4.7.3'
    pod 'SwiftyJSON', '4.1.0'
    pod 'Cartography', '3.0.2'
    pod 'Kingfisher', '4.9.0'
    pod 'SwiftyUserDefaults', '3.0.1'
    pod 'GoogleMaps', '2.7.0'
    pod 'SwiftIcons', '2.2.0'
    pod 'Toast-Swift', '3.0.1'
end
